name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11.0

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      
      - name: Tap Repository
        run: brew tap fwartner/mac-cleanup
        
      - name: Install mac-cleanup
        run: brew install fwartner/mac-cleanup
