name: Update Homebrew Formula

on:
  release:
    types:
      - created

jobs:
  formula:
    name: Update Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: fwartner/homebrew-mac-cleanup
          tap: fwartner/homebrew-mac-cleanup
          formula: formula/mac-cleanup.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
