name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  homebrew-release:
    runs-on: macOS-latest
    steps:
      - name: Release Homebrew Formula
          if: github.event.release.prerelease != true
          uses: garden-io/update-homebrew-action@v1
          with:
            packageName: 'mac-cleanup'
            templatePath: 'formula/mac-cleanup.rb'
            tapRepo: 'fwartner/homebrew-mac-cleanup'
            srcRepo: 'fwartner/homebrew-mac-cleanup'
            authToken: ${{ secrets.GITHUB_TOKEN }}
