name: Release

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release my project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: fwartner
          homebrew_tap: homebrew-tap
          formula_folder: formula
          github_token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          commit_owner: "Florian Wartner"
          commit_email: florian@wartner.io
          install: 'bin.install "src/my-script.sh" => "my-script"'
          test: 'assert_match("my script output", shell_output("my-script-command"))'
          skip_commit: false
          update_readme_table: true
