name: Release

on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: fwartner/mac-cleanup
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

